name: First Workflow

on: push

env:
  TEST1: "hello from workflow"

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variable 
        run: echo "TEST =  ${{ vars.TEST1 }}"
      
      - name: Print Secret
        env:
          MY_SECRET: "${{ secrets.MY_SECRET }}"
        run: echo "MY_SECRET = $MY_SECRET"
  test: 
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Print Env specific Variable
        env:
          VAR: ${{ vars.MY_ENV_VAR }}
        run: echo "MY_ENV_VAR = $VAR"
  
  prod: 
    runs-on: ubuntu-latest
    environment: PROD 
    steps:
      - name: Print Env specific Variable
        env:
          VAR: ${{ vars.MY_ENV_VAR }}
        run: echo "MY_ENV_VAR = $VAR"
