name: First Workflow

on: push

env:
  TEST1: "hello from workflow"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Print Variable 
        run: echo "TEST =  ${{ vars.TEST1 }}"
      
      - name: Print Secret
        env:
          MY_SECRET: "${{ secrets.MY_SECRET }}"
        run: echo "MY_SECRET = $MY_SECRET"

      - name: Print Env specific Variable
        run: echo "MY_TEST_VAR = ${{ vars.MY_TEST_VAR }}"
